name: Compile & Release

on:
    push:
        paths:
            - '**.gradle'
            - '**.properties'
            - '**/src/**'
            - '.github/**'
        branches:
            - v4
            - v5
            - v6
            - v7
            - v8
            - v9
            - v10
            - v11-23w13ab
            - v11
            - v12
            - v13
            - v14
            - v14-24w14potato
            - v15
            - v16
            - v17

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 21
              uses: actions/setup-java@v2
              with:
                  java-version: 21
                  distribution: 'temurin'
            - name: Upload to Maven
              run: ./gradlew publish modPublish --stacktrace
              if: |
                  !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
              env:
                  MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
                  curse_api_key: ${{ secrets.CF_API_KEY }}
                  modrinth_key: ${{ secrets.MODRINTH_KEY }}
